### ISSUE TITLE
PDF RMARKDOWN

### ISSUE THREAD

**Issue by essekarobe** [essekarobe/trabajo01grupotd2024#6]
Tengo problemas para hacer knit desde mi pc ¿alguien puede exportar los .Rmd con mis enunciados y resoluciones? Gracias!

**Comment by laumaydel** [comment]
Solucionado, bastaba con eliminar la línea library(KableExtra) pues falla a la hora de compilar el PDF. Supongo que la habrás usado para poner las tablas de forma más "estética" pero solo es necesario poner knitr::kable(tabla) para que se vean bien en el PDF.
